version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: home_budget_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "2022:5432"